services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-cont
    environment:
      SA_PASSWORD: "StrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  webapp:
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    container_name: webapp
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=UserDb;User Id=sa;Password=StrongPassword123!
